loja/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover após DEBUG toolbar
urlpatterns += debug_toolbar_urls()

produto/urls.py
from django.urls import path
from . import views

app_name='produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionar_carrinho/', views.AdicionarCar.as_view(), 
        name='adicionar_carrinho'),
    path('remover_carrinho/', views.RemoverCar.as_view(), 
        name='remover_carrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('finalizar/', views.Finalizar.as_view(), name='finalizar'),
]

produto/models.py
from django.db import models
from django.conf import settings
from utils.random import slugify_new
from utils import help
from PIL import Image
import os

class Produto(models.Model):
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    nome = models.CharField(max_length=255)
    short_description = models.TextField(
        max_length=255, 
        blank=True, 
        null=True,
        verbose_name='Descrição curta',
    )
    long_description = models.TextField(blank=True, null=True,)
    image = models.ImageField(
        upload_to='produto_imagems/%Y/%m', 
        blank=True, 
        null=True,
        )
    slug = models.SlugField(unique=True, blank=True, null=True, max_length=255)
    marketing_price = models.FloatField()
    promotional_price = models.FloatField(default=0,)
    category = models.CharField(
        default='V', max_length=1, 
        choices=[
            ('V', 'Variavel'), ('S', 'Simples'),
        ]
    )

    def get_price_format(self):
        return help.format_price(self.marketing_price)
    get_price_format.short_description = 'Preço'

    def get_promotional_price(self):
        return help.format_price(self.promotional_price)
    get_promotional_price.short_description = 'Preço Promo'

    @staticmethod
    def resize_image(img, size=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pill = Image.open(img_full_path)
        original_width, original_height = img_pill.size

        if original_width <= size:
            img_pill.close()
            return

        new_height = round((size * original_height) / original_width)
        new_img = img_pill.resize((size, new_height), Image.LANCZOS)

        new_img.save(
            img_full_path,
            optimize=True,
            quality=50,
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify_new(self.nome, 5)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.image:
            self.resize_image(self.image, max_image_size)

    def __str__(self):
        return self.nome
    
class Variacao(models.Model):
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

    product = models.ForeignKey(Produto, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)


    def __str__(self):
        return self.name or self.product.nome

produto/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView 
from django.views import View
from django.http import HttpResponse
from . import models

# Create your views here.

class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 9

class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class AdicionarCar(View):
    def get(self, *args, **kwargs):
        return HttpResponse("Adicionar ao Carrinho")

class RemoverCar(View):
    def get(self, *args, **kwargs):
        return HttpResponse("Remover do Carrinho")

class Carrinho(View):
    def get(self, *args, **kwargs):
        return HttpResponse("Carrinho")

class Finalizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse("Finalizar compra")

produto/templates/produto/detalhe.html
{% extends "base.html" %}
{% load lsfilters %}

{% block conteiner %}
<div class="row">
    <div class="col-lg-12">
    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    {% if produto.image %}
                    <img class="img-fluid" src="{{ produto.image.url }}" alt="{{ produto.nome }}">
                    {% else %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg">
            <div class="mt-4 mt-lg-0">
                <h1 class="h2">{{ produto.nome }}</h1>
                <p class="lead">{{produto.short_description}}</p>
                    <p class="lead">
                        {% if produto.promotional_price %}
                        <span id="variation-preco" class="lead product-price">
                            {{produto.promotional_price | format_price}}
                        </span>
                        <span id="variation-preco-promocional"
                            class="lead product-old-price text-muted">
                            {{produto.marketing_price | format_price}}
                        </span>
                        {% else %}
                        <span id="variation-preco" class="lead product-price">{{produto.marketing_price | format_price}}</span>
                        {% endif %}
                    </p>
                    
                    <form action="/addtocart/" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">

                                {% for variacao in produto.variacao_set.all %}
                                {% if variacao.promotional_price %}
                                <option 
                                    data-preco="{{variacao.promotional_price|format_price}}" 
                                    data-preco-promocional="{{variacao.price|format_price}}" 
                                    value="{{variacao.id}}">{{variacao}}
                                </option>
                                {% else %}
                                    <option 
                                    
                                    data-preco="{{variacao.price|format_price}}" 
                                    value="{{variacao.id}}">{{variacao}}
                                </option>
                                {% endif %}
                                {% endfor %}
                                
                            </select>
                        </div>
                        
                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>
                        
                    </form>
                    
                    
            </div>
        </div>
        </div>
        
        
    <div class="row">
        <div class="col-lg-12">
            <div class="mt-5 mb-5">
                <h2 class="text-center">Descrição</h2>
                <p>
                    {{ produto.long_description|linebreaks }}
                </p>
                        
            </div>
            </div>
        </div>
                            
    </div>
</div>
{% endblock conteiner %}

produto/templates/produto/lista.html
{% extends "base.html" %}
{% load lsfilters %}

{% block conteiner %}
    <div class="row">
            <div class="col-lg-12">
                <div class="card-columns">
                    
                    {% for produto in produtos %}
                    <div class="card">
                        {% if produto.image %}
                        <a href="{{produto.slug}}">
                            <img class="card-img-top" src="{{ produto.image.url }}" 
                            alt="{{produto.nome}}">
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{produto.nome}}</h5>
                            <p class="card-text">{{produto.short_description}}</p>
                                <div class="container product-price-block text-center">

                                    {% if produto.promotional_price %}
                                    <span class="product-price">
                                        {{ produto.promotional_price | format_price}}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ produto.marketing_price | format_price}}
                                    </span>
                                    {% else %}
                                    <span class="product-price">
                                        {{ produto.marketing_price | format_price}}
                                    </span>
                                    {% endif %}

                                </div>
                            </div>
                            <div class="card-footer bg-transparent border-top-light-custom text-center">
                                <a href="{{produto.slug}}" class="btn btn-primary btn-sm m-1 btn-block">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Comprar
                                </a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col">
                {% include "parciais/_pagination.html" %}
            </div>
        </div>
{% endblock conteiner %}